=== usamariazch87/XML-DTD-Assignment/external.dtd
<!ELEMENT paktech (employee+, client?)>
    <!ELEMENT employee (name, (email|number), password)>
    <!ELEMENT client (name, email, password)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT password (#PCDATA)>
<!ATTLIST email domain CDATA #REQUIRED>

=== usamariazch87/XML-DTD-Assignment/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paktech SYSTEM "external.dtd" [

<!ENTITY ps "pass1122">
]>

<paktech>
    <employee>
        <name>aliya</name>
        <email domain="https://www.hehe.com">aliya@gmail.com</email>
        <password>a22222</password>
    </employee>
    <employee>
        <name>farah</name>
        <number>02233443</number>
        <password>a26622</password>
    </employee>
    <employee>
        <name>sana</name>
        <email domain="https://www.hehe.com">sana@gmail.com</email>
        <password>a24422</password>
    </employee>
    <client>
        <name>saira</name>
        <email domain="https://www.hehe.com">saira@gmail.com</email>
        <password>&ps;</password>
    </client>
</paktech>
